version: "3"

services: 
  api-solid-pg:
    image: bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid
    ports:
      - 5432:5432
    # volumes:
    #   - 'api-solid-pg_data:/bitnami/postgresql'